"""add rating and review to opponents

Revision ID: add_rating_review
Revises: add_role_total_goals
Create Date: 2024-01-15 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_rating_review'
down_revision = 'add_role_total_goals'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opponents', sa.Column('rating', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('opponents', sa.Column('review', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opponents', 'review')
    op.drop_column('opponents', 'rating')
    # ### end Alembic commands ###

