"""add role and total_goals to players

Revision ID: add_role_total_goals
Revises: add_is_completed
Create Date: 2024-01-15 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_role_total_goals'
down_revision = 'add_is_completed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('role', sa.String(), nullable=False, server_default='Cầu thủ'))
    op.add_column('players', sa.Column('total_goals', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'total_goals')
    op.drop_column('players', 'role')
    # ### end Alembic commands ###

