"""add match_goals table

Revision ID: add_match_goals
Revises: 45d7992c5747
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_match_goals'
down_revision = '45d7992c5747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_goals_id'), 'match_goals', ['id'], unique=False)
    op.create_index(op.f('ix_match_goals_match_id'), 'match_goals', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_goals_player_id'), 'match_goals', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_goals_player_id'), table_name='match_goals')
    op.drop_index(op.f('ix_match_goals_match_id'), table_name='match_goals')
    op.drop_index(op.f('ix_match_goals_id'), table_name='match_goals')
    op.drop_table('match_goals')
    # ### end Alembic commands ###

